name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Some input'
        required: true
        default: 'main'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo calculated version
        run: |
          echo "Current version: ${{ steps.version.outputs.current-version }}"
          echo "Next version: ${{ steps.version.outputs.next-version }}"
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create release
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
        #   config-name: my-config.yml
          name: ${{ format('v{0}', steps.version.outputs.next-version) }}
          tag: ${{ format('{0}', steps.version.outputs.next-version) }}
          version: ${{ format('v{0}', steps.version.outputs.next-version) }}
          #publish: ${{ }}
          commitish: ${{ github.ref }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
