name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Some input'
        required: true
        default: 'main'

jobs:
  update_release_draft:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Calculate next version
      #  id: version
      #  uses: patrickjahns/version-drafter-action@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate release version
        id: version
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          commitish: ${{ github.ref }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo calculated version
        run: |
          echo "id: ${{ steps.version.outputs.id }}"
          echo "name: ${{ steps.version.outputs.name }}"
          echo "tag_name: ${{ steps.version.outputs.tag_name }}"
          echo "body: ${{ steps.version.outputs.body }}"
          echo "html_url: ${{ steps.version.outputs.html_url }}"
          echo "upload_url: ${{ steps.version.outputs.upload_url }}"

      - name: Add release commit
        run: |
          echo "${{ steps.version.outputs.tag_name }}" > version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[RELEASE] ${{ steps.version.outputs.name }}"
          git push

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create release
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
        #   config-name: my-config.yml
          #name: ${{ format('v{0}', steps.version.outputs.next-version) }}
          #tag: ${{ format('{0}', steps.version.outputs.next-version) }}
          #version: ${{ format('v{0}', steps.version.outputs.next-version) }}
          #publish: ${{ }}
          commitish: ${{ github.ref }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
